/*
 * Copyright (c) 2022, salesforce.com, inc.
 * All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 */
@IsTest
private class MockTest {
  @IsTest
  static void IntegrationTest() {
    // given A Type
    // when Sypying On Method
    // Then Return The

    // Use case 1
    // Arrange
    // Create a mock
    // Parameter its return

    // Act
    // Call the method

    // Assert
    // Assert result is the same as returned

    /////////////
    // Use case 2
    // Arrange
    // Create a mock
    // Do not Parameter its return

    // Act
    // Call the method

    // Assert
    // Assert result null
  }

  @IsTest
  static void UnitTest() {
    // given A method name
    // when Sypying On Method multiple time
    // The method Spy returned is the same

    // Use case 1
    // Arrange
    // Create a mock
    // SpyOn a Method

    // Act
    // SpyOn the same Method

    // Assert
    // Assert result is the same as the first spyOn
  }
}
