/*
 * Copyright (c) 2022, salesforce.com, inc.
 * All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 */
@IsTest
private class ParameterizedMethodSpyCallTest {
  // Two identical list by reference

  // Two identical list by content

  // Two different list

  // DTO use case
  // Two same custom list with custom apex
  // Two different custom list with custom apex

  // Two same custom list with custom apex not supporting JSON serialization
  // Two different custom list with custom apex  not supporting JSON serialization

  // Check if serialize is good compared to serializeUntyped (type checking for JSON serialize)

  // When calling `thenReturn` it changes value of `returnValue`
}
