name: build
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        run: |
          echo "SFDX_DISABLE_AUTOUPDATE=true" >> $GITHUB_ENV
          echo "SFDX_DISABLE_SOURCE_MEMBER_POLLING=true" >> $GITHUB_ENV
          echo "SFDX_DISABLE_TELEMETRY=true" >> $GITHUB_ENV

      - name: Install sfdx and connect to DevHub
        run: |
          npm install --global sfdx-cli@${{ vars.SFDX_VERSION }}
          echo ${{ secrets.DEVHUB_URL }} > sfdx_auth
          sfdx force:auth:sfdxurl:store --sfdxurlfile sfdx_auth --setdefaultdevhubusername --setalias hub
          sfdx config:set defaultdevhubusername=hub --global

      - name: Checkout
        uses: actions/checkout@v4

      - name: Create scratch org
        run: sfdx force:org:create --nonamespace --definitionfile config/project-scratch-def.json --setalias scratch-org --setdefaultusername --durationdays 1

      - name: Push source to scratch org
        run: sfdx force:source:push

      - name: Run Apex tests
        run: npm run test

      - name: Delete scratch org
        if: always()
        run: sfdx force:org:delete --noprompt
