name: create package version
on:
  workflow_call:
    inputs:
      branch:
        type: string
        default: ${{ github.head_ref }}
      packageAlias:
        required: true
        type: string
    outputs:
      packageId:
        description: 04t package version id created
        value: ${{ jobs.create-package-version.outputs.packageId }}

jobs:
  create-package-version:
    runs-on: ubuntu-latest
    outputs:
      packageId: ${{ steps.create.outputs.packageId }}
    steps:
      - name: Set environment variables
        run: |
          echo "SF_DISABLE_AUTOUPDATE=true" >> $GITHUB_ENV
          echo "SF_DISABLE_SOURCE_MEMBER_POLLING=true" >> $GITHUB_ENV
          echo "SF_DISABLE_TELEMETRY=true" >> $GITHUB_ENV
          echo "SF_PROJECT_AUTOUPDATE_DISABLE_FOR_PACKAGE_VERSION_CREATE=true" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install sfdx and connect to DevHub
        run: |
          npm install --global @salesforce/cli@${{ vars.SFDX_VERSION }}
          echo ${{ secrets.DEVHUB_URL }} > sfdx_auth
          sf org login sfdx-url --sfdx-url-file sfdx_auth --set-default-dev-hub --alias hub
          sf config set target-dev-hub=hub --global

      - name: Create package version
        id: create
        run: |
          packageId=$(sf package version create --definition-file config/project-scratch-def.json --package "${{ inputs.packageAlias }}" --branch "${{ inputs.branch }}" --tag ${{ github.sha }} --wait 120 --code-coverage --skip-ancestor-check --installation-key-bypass --json | jq -e -r ".result.SubscriberPackageVersionId")
          echo "packageId=$packageId" >> $GITHUB_ENV
          echo "packageId=$packageId" >> $GITHUB_OUTPUT
