name: create package version
on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
    outputs:
      packageId:
        description: 04t package version id created
        value: ${{ jobs.create-package-version.outputs.packageId }}

jobs:
  create-package-version:
    runs-on: ubuntu-latest
    outputs:
      packageId: ${{ steps.create.outputs.packageId }}
    steps:
      - name: Set environment variables
        run: |
          echo "SFDX_DISABLE_AUTOUPDATE=true" >> $GITHUB_ENV
          echo "SFDX_DISABLE_SOURCE_MEMBER_POLLING=true" >> $GITHUB_ENV
          echo "SFDX_DISABLE_TELEMETRY=true" >> $GITHUB_ENV
          echo "SFDX_PROJECT_AUTOUPDATE_DISABLE_FOR_PACKAGE_VERSION_CREATE=true" >> $GITHUB_ENV

      - name: Install sfdx and connect to DevHub
        run: |
          npm install --global sfdx-cli
          echo ${{ secrets.DEVHUB_URL }} > sfdx_auth
          sfdx force:auth:sfdxurl:store -f sfdx_auth -d -a hub
          sfdx config:set defaultdevhubusername=hub --global

      - name: Checkout
        uses: actions/checkout@v3

      - name: Create package version
        id: create
        run: |
          packageId=$(sfdx force:package:version:create --definitionfile config/project-scratch-def.json --package "Apex Mockery" --branch "${{ inputs.branch }}" --tag ${{ github.sha }} --wait 120 --codecoverage --skipancestorcheck --installationkeybypass --json | jq -e -r ".result.SubscriberPackageVersionId")
          echo "packageId=$packageId" >> $GITHUB_ENV
          echo "packageId=$packageId" >> $GITHUB_OUTPUT

      - name: Create scratch org
        run: sfdx force:org:create -f config/project-scratch-def.json -a scratch-org -s -d 1

      - name: Check package installation
        run: sfdx force:package:install -p ${{ env.packageId }} -u scratch-org -w 10

      - name: Delete scratch org
        if: always()
        run: sfdx force:org:delete -p -u scratch-org
