name: main

on:
  push:
    branches: [main]
    tags-ignore:
      - '**'

jobs:
  integrate:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  create-namespaced-package-version:
    uses: ./.github/workflows/create-package-version.yml
    needs: integrate
    with:
      packageAlias: Apex Mockery NS Test
    secrets: inherit

  validate-namespace-compatibility:
    uses: ./.github/workflows/validate-namespace-compatibility.yml
    needs: create-namespaced-package-version
    with:
      packageId: ${{ needs.create-namespaced-package-version.outputs.packageId }}
    secrets: inherit

  create-package-version:
    uses: ./.github/workflows/create-package-version.yml
    needs: integrate
    with:
      packageAlias: Apex Mockery
    secrets: inherit

  validate-package-version:
    uses: ./.github/workflows/validate-package-version.yml
    needs: create-package-version
    with:
      packageId: ${{ needs.create-package-version.outputs.packageId }}
    secrets: inherit

  prepare-release:
    needs: [validate-package-version, validate-namespace-compatibility]
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          release-type: sfdx
          package-name: apex-mockery