name: validate package version
on:
  workflow_call:
    inputs:
      packageId:
        required: true
        description: 04t package version id created
        type: string

jobs:
  validate-package-version:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        run: |
          echo "SFDX_DISABLE_AUTOUPDATE=true" >> $GITHUB_ENV
          echo "SFDX_DISABLE_SOURCE_MEMBER_POLLING=true" >> $GITHUB_ENV
          echo "SFDX_DISABLE_TELEMETRY=true" >> $GITHUB_ENV
          echo "SFDX_PROJECT_AUTOUPDATE_DISABLE_FOR_PACKAGE_VERSION_CREATE=true" >> $GITHUB_ENV

      - name: Install sfdx and connect to DevHub
        run: |
          npm install --global sfdx-cli@${{ vars.SFDX_VERSION }}
          echo ${{ secrets.DEVHUB_URL }} > sfdx_auth
          sfdx force:auth:sfdxurl:store -f sfdx_auth -d -a hub
          sfdx config:set defaultdevhubusername=hub --global

      - name: Checkout
        uses: actions/checkout@v3

      - name: Create scratch org
        run: sfdx force:org:create -f config/project-scratch-def.json -a scratch-org -s -d 1

      - name: Check package installation
        run: sfdx force:package:install -p ${{ inputs.packageId }} -u scratch-org -w 10

      - name: Deploy namespaced recipes
        run: sfdx force:source:deploy -p force-app/recipes

      - name: Execute tests
        run: sfdx force:apex:test:run -r human -d ./tests/apex -l RunLocalTests -w 20

      - name: Delete scratch org
        if: always()
        run: sfdx force:org:delete -p -u scratch-org
